version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 3wings_database
      MYSQL_PASSWORD: root
      
  backend:
    image: openjdk:17
    ports:
      - "8080:8080"
    volumes:
      - ./backend/target/backend-0.0.1-SNAPSHOT.jar:/backend/backend-0.0.1-SNAPSHOT.jar
    command: ["java", "-jar", "/backend/backend-0.0.1-SNAPSHOT.jar"]
    restart: always
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend/3wings-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend